/*
 * Copyright (c) 2026 Cadbos company. All rights reserved.
 *
 * SPDX-License-Identifier: LicenseRef-Cadbos-BSL-1.1
 *
 * Cadbos Interior Design AI is licensed under the Business Source License 1.1.
 * Access is limited to automated analysis tools for analysis of this repository.
 * This code is not open for contribution or usage except under a separate
 * written agreement with Cadbos company.
 *
 * Commercial use in Interior Design & AEC Generative AI Services is prohibited
 * before the Change Date. See LICENSE for complete terms.
 */

import type { EditIntent } from '$lib/mode-hints';

export const INTENT_CORPUS: readonly [string, EditIntent | null][] = [
	['добавь стол у окна', 'add'],
	['поставь кресло возле камина', 'add'],
	['повесь люстру над обеденным столом', 'add'],
	['подвесь светильник над островом', 'add'],
	['положи плед на диван', 'add'],
	['размести пуф у кровати', 'add'],
	['вставь камин в стену', 'add'],
	['дорисуй ковёр на полу', 'add'],
	['нужен журнальный столик', 'add'],
	['нужна тумба под телевизор', 'add'],
	['пусть будет кресло-качалка в углу', 'add'],
	['хочу, чтобы здесь стоял рояль', 'add'],
	['хочу чтобы тут был камин', 'add'],
	['пусть появится барная стойка', 'add'],
	['Добавьте, пожалуйста, торшер', 'add'],
	['добавить ковёр', 'add'],
	['add a coffee table', 'add'],
	['place an armchair by the fireplace', 'add'],
	['put a rug under the bed', 'add'],
	['hang a chandelier above the table', 'add'],
	['insert a fireplace into the wall', 'add'],
	['mount a TV on the wall', 'add'],
	['adding a bench near the window', 'add'],

	['убери диван', 'remove'],
	['уберите ковёр', 'remove'],
	['удали стул у окна', 'remove'],
	['удалить телевизор', 'remove'],
	['сотри надпись на стене', 'remove'],
	['избавься от проводов', 'remove'],
	['вынеси коробки из комнаты', 'remove'],
	['выкинь старый шкаф', 'remove'],
	['спрячь провода', 'remove'],
	['очисти стол от вещей', 'remove'],
	['хочу, чтобы не было ковра', 'remove'],
	['убрать людей', 'remove'],
	['remove the chair', 'remove'],
	['delete the lamp', 'remove'],
	['erase the text on the wall', 'remove'],
	['get rid of the clutter', 'remove'],
	['take out the old TV', 'remove'],
	['declutter the shelves', 'remove'],
	['clear out the boxes', 'remove'],

	['замени диван на кресло', 'replace'],
	['поменяй стол на круглый', 'replace'],
	['смени люстру на подвесные лампы', 'replace'],
	['кресло вместо дивана', 'replace'],
	['на место шкафа поставь стеллаж', 'replace'],
	['убери старый диван и поставь новый', 'replace'],
	['replace the sofa with a sectional', 'replace'],
	['swap the chairs for stools', 'replace'],
	['a bench instead of the chairs', 'replace'],
	['change the sofa to a leather one', 'replace'],

	['перекрась стены в белый', 'recolor'],
	['покрась потолок в голубой', 'recolor'],
	['окрась фасад', 'recolor'],
	['перетяни диван в бархат', 'recolor'],
	['поменяй цвет стен', 'recolor'],
	['смени обивку кресел', 'recolor'],
	['измени текстуру пола', 'recolor'],
	['замени материал столешницы', 'recolor'],
	['сделай стены белыми', 'recolor'],
	['сделай диван зелёного цвета', 'recolor'],
	['сделай пол под дерево', 'recolor'],
	['сделай кухонные фасады матовыми', 'recolor'],
	['repaint the walls white', 'recolor'],
	['paint the ceiling blue', 'recolor'],
	['recolor the sofa', 'recolor'],
	['reupholster the armchair in velvet', 'recolor'],
	['change the color of the walls', 'recolor'],
	['change the texture of the floor', 'recolor'],
	['make the cabinets matte', 'recolor'],
	['turn the walls beige', 'recolor'],

	['сделай тёплое освещение', 'light'],
	['больше света', 'light'],
	['включи люстру', 'light'],
	['выключи торшер', 'light'],
	['зажги свечи', 'light'],
	['погаси свет в коридоре', 'light'],
	['приглуши освещение', 'light'],
	['как на закате', 'light'],
	['вечерняя атмосфера', 'light'],
	['ночной вид', 'light'],
	['утреннее солнце', 'light'],
	['пасмурный день за окном', 'light'],
	['сделай комнату светлее', 'light'],
	['сделай интерьер темнее', 'light'],
	['добавь тёплый свет над картиной', 'light'],
	['добавь праздничную подсветку', 'light'],
	['warm lighting', 'light'],
	['turn on the lamps', 'light'],
	['switch off the chandelier', 'light'],
	['dim the lights', 'light'],
	['brighten the room', 'light'],
	['make the room brighter', 'light'],
	['sunset glow through the window', 'light'],
	['night scene', 'light'],
	['add warm light above the painting', 'light'],

	['в стиле лофт', 'style'],
	['сделай в стиле сканди', 'style'],
	['скандинавский интерьер', 'style'],
	['минимализм и много воздуха', 'style'],
	['прованс', 'style'],
	['хай-тек', 'style'],
	['бохо-гостиная', 'style'],
	['джапанди', 'style'],
	['неоклассика с лепниной', 'style'],
	['ар-деко', 'style'],
	['индустриальный стиль', 'style'],
	['средиземноморская атмосфера', 'style'],
	['in a loft style', 'style'],
	['scandinavian interior', 'style'],
	['minimalist and airy', 'style'],
	['japandi', 'style'],
	['art deco', 'style'],
	['mid-century modern', 'style'],
	['industrial vibe', 'style'],

	['серый диван у окна', null],
	['старый диван', null],
	['обивка дивана', null],
	['светлый ламинат', null],
	['светильник над столом', null],
	['лампа на тумбе', null],
	['ночник у кровати', null],
	['кресло у камина', null],
	['большое зеркало в прихожей', null],
	['диван, включая подушки', null],
	['современная гостиная с большими окнами', null],
	['уютная спальня', null],
	['сделай современную гостиную в белых тонах', null],
	['диван цвета слоновой кости', null],
	['не добавляй ничего лишнего', null],
	['ничего не убирай', null],
	['light gray sofa by the window', null],
	['light oak table', null],
	['the old sofa', null],
	['sofa upholstery', null],
	['a cozy bedroom', null],
	['painting above the sofa', null],
	['placement of furniture looks good', null],
	["don't remove anything", null],

	['поставь диван у окна вместо кресла', 'replace'],
	['сделай свет теплее', 'light'],
	['покрась стены как на референсе', 'recolor'],
	['добавь немного зелени', 'add'],
	['добавь людей в движении', 'add'],
	['add some plants', 'add'],
	['убери всё лишнее', 'remove'],
	['светлая кухня в стиле лофт', 'style'],
	['the room should feel brighter', 'light'],
	['сделай стены цвета графит', 'recolor'],
	['дверь не трогай, перекрась стены', 'recolor'],
	['не нужно ничего добавлять', null],
	['не надо ничего убирать', null],
	['no need to add anything', null],
	['сделай потолок выше', null],
	['make it cozier', null],
	['хочу больше зелени', null],
	['в белом цвете', null]
];
