// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.myarchitectai.com/v1' | (string & {});
};

export type RenderInteriorInput = {
    /**
     * URL of the source image (sketch, drawing, or photo)
     */
    image: string;
    /**
     * Output image format
     */
    outputFormat: 'webp' | 'jpg' | 'png' | 'avif';
    /**
     * Text prompt to guide the interior render style and elements
     */
    prompt?: string;
};

export type GatewayErrorResponse = {
    /**
     * Error message returned by the API gateway
     */
    message: string;
};

export type ErrorResponse = {
    /**
     * Error message describing what went wrong
     */
    error: string;
    /**
     * Remaining account balance
     */
    balance: number;
    /**
     * Cost charged for this request (typically 0 on error)
     */
    cost: number;
};

export type SingleGenerationResponse = {
    /**
     * URL of the generated image (or video, for /animate)
     */
    output: string;
    /**
     * Remaining account balance after this request
     */
    balance: number;
    /**
     * Cost charged for this request
     */
    cost: number;
};

export type ArrayGenerationResponse = {
    /**
     * List of generated image URLs
     */
    output: Array<string>;
    /**
     * Remaining account balance after this request
     */
    balance: number;
    /**
     * Cost charged for this request
     */
    cost: number;
};

export type Upscale4kInput = {
    /**
     * URL of the source image to upscale
     */
    image: string;
    /**
     * Output image format. Defaults to jpg if omitted
     */
    outputFormat?: 'webp' | 'jpg' | 'png' | 'avif';
};

export type TextToImageInput = {
    /**
     * Text description of the architectural image to generate
     */
    prompt: string;
    /**
     * Output image format (avif is not supported for text-to-image)
     */
    outputFormat: 'png' | 'jpg' | 'webp';
    /**
     * Output image height in pixels
     */
    outputHeight: number;
    /**
     * Output image width in pixels
     */
    outputWidth: number;
    /**
     * Text describing elements to exclude from the generated image
     */
    negativePrompt?: string;
};

export type RenderInput = {
    /**
     * URL of the source image (sketch, drawing, or photo)
     */
    image: string;
    /**
     * Output image format
     */
    outputFormat: 'webp' | 'jpg' | 'png' | 'avif';
    /**
     * Text prompt to guide the exterior render style and elements
     */
    prompt?: string;
};

export type StyleTransferInput = {
    /**
     * URL of the source architectural image
     */
    image: string;
    /**
     * Output image format
     */
    outputFormat: 'webp' | 'jpg' | 'png' | 'avif';
    /**
     * URL of the style reference image to transfer from
     */
    referenceImage: string;
    /**
     * Text prompt to guide the style transfer
     */
    prompt?: string;
    /**
     * Text describing elements to exclude from the output
     */
    negativePrompt?: string;
    /**
     * How strongly to apply the reference style (0 = no effect, 1 = full transfer)
     */
    styleTransferStrength?: number;
};

export type EditByPromptInput = {
    /**
     * URL of the source image to edit
     */
    image: string;
    /**
     * Natural-language instruction describing the edit to apply
     */
    prompt: string;
};

export type AnimateInput = {
    /**
     * URL of the source image used as the start frame of the video
     */
    startFrameUrl: string;
    /**
     * Text prompt describing the motion to animate
     */
    prompt: string;
    /**
     * Optional URL of an image to use as the end frame. When provided, the video interpolates from the start frame to this frame.
     */
    endFrameUrl?: string;
};

export type AutoPromptInput = {
    /**
     * URL of the source image to analyze
     */
    image: string;
};

export type AutoPromptResponse = {
    /**
     * The generated comma-separated render prompt (plain text, not a URL)
     */
    output: string;
    /**
     * Remaining account balance after this request
     */
    balance: number;
    /**
     * Cost charged for this request
     */
    cost: number;
};

export type PostRenderInteriorData = {
    body: RenderInteriorInput;
    path?: never;
    query?: never;
    url: '/render/interior';
};

export type PostRenderInteriorErrors = {
    /**
     * Generation failed due to invalid input or processing error
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key
     */
    403: GatewayErrorResponse;
    /**
     * Internal server error
     */
    500: GatewayErrorResponse;
};

export type PostRenderInteriorError = PostRenderInteriorErrors[keyof PostRenderInteriorErrors];

export type PostRenderInteriorResponses = {
    /**
     * Successful generation
     */
    200: ArrayGenerationResponse;
};

export type PostRenderInteriorResponse = PostRenderInteriorResponses[keyof PostRenderInteriorResponses];

export type PostRenderExteriorData = {
    body: RenderInput;
    path?: never;
    query?: never;
    url: '/render/exterior';
};

export type PostRenderExteriorErrors = {
    /**
     * Generation failed due to invalid input or processing error
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key
     */
    403: GatewayErrorResponse;
    /**
     * Internal server error
     */
    500: GatewayErrorResponse;
};

export type PostRenderExteriorError = PostRenderExteriorErrors[keyof PostRenderExteriorErrors];

export type PostRenderExteriorResponses = {
    /**
     * Successful generation
     */
    200: ArrayGenerationResponse;
};

export type PostRenderExteriorResponse = PostRenderExteriorResponses[keyof PostRenderExteriorResponses];

export type PostAutoPromptData = {
    body: AutoPromptInput;
    path?: never;
    query?: never;
    url: '/auto-prompt';
};

export type PostAutoPromptErrors = {
    /**
     * Generation failed due to invalid input or processing error
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key
     */
    403: GatewayErrorResponse;
    /**
     * Internal server error
     */
    500: GatewayErrorResponse;
};

export type PostAutoPromptError = PostAutoPromptErrors[keyof PostAutoPromptErrors];

export type PostAutoPromptResponses = {
    /**
     * Successful generation
     */
    200: AutoPromptResponse;
};

export type PostAutoPromptResponse = PostAutoPromptResponses[keyof PostAutoPromptResponses];

export type PostEditByPromptData = {
    body: EditByPromptInput;
    path?: never;
    query?: never;
    url: '/edit-by-prompt';
};

export type PostEditByPromptErrors = {
    /**
     * Generation failed due to invalid input or processing error
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key
     */
    403: GatewayErrorResponse;
    /**
     * Internal server error
     */
    500: GatewayErrorResponse;
};

export type PostEditByPromptError = PostEditByPromptErrors[keyof PostEditByPromptErrors];

export type PostEditByPromptResponses = {
    /**
     * Successful generation
     */
    200: SingleGenerationResponse;
};

export type PostEditByPromptResponse = PostEditByPromptResponses[keyof PostEditByPromptResponses];

export type PostStyleTransferData = {
    body: StyleTransferInput;
    path?: never;
    query?: never;
    url: '/style-transfer';
};

export type PostStyleTransferErrors = {
    /**
     * Generation failed due to invalid input or processing error
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key
     */
    403: GatewayErrorResponse;
    /**
     * Internal server error
     */
    500: GatewayErrorResponse;
};

export type PostStyleTransferError = PostStyleTransferErrors[keyof PostStyleTransferErrors];

export type PostStyleTransferResponses = {
    /**
     * Successful generation
     */
    200: ArrayGenerationResponse;
};

export type PostStyleTransferResponse = PostStyleTransferResponses[keyof PostStyleTransferResponses];

export type PostAnimateData = {
    body: AnimateInput;
    path?: never;
    query?: never;
    url: '/animate';
};

export type PostAnimateErrors = {
    /**
     * Generation failed due to invalid input or processing error
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key
     */
    403: GatewayErrorResponse;
    /**
     * Internal server error
     */
    500: GatewayErrorResponse;
};

export type PostAnimateError = PostAnimateErrors[keyof PostAnimateErrors];

export type PostAnimateResponses = {
    /**
     * Successful generation
     */
    200: SingleGenerationResponse;
};

export type PostAnimateResponse = PostAnimateResponses[keyof PostAnimateResponses];

export type PostUpscale4kData = {
    body: Upscale4kInput;
    path?: never;
    query?: never;
    url: '/upscale-4k';
};

export type PostUpscale4kErrors = {
    /**
     * Generation failed due to invalid input or processing error
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key
     */
    403: GatewayErrorResponse;
    /**
     * Internal server error
     */
    500: GatewayErrorResponse;
};

export type PostUpscale4kError = PostUpscale4kErrors[keyof PostUpscale4kErrors];

export type PostUpscale4kResponses = {
    /**
     * Successful generation
     */
    200: SingleGenerationResponse;
};

export type PostUpscale4kResponse = PostUpscale4kResponses[keyof PostUpscale4kResponses];

export type PostTextToImageData = {
    body: TextToImageInput;
    path?: never;
    query?: never;
    url: '/text-to-image';
};

export type PostTextToImageErrors = {
    /**
     * Generation failed due to invalid input or processing error
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key
     */
    403: GatewayErrorResponse;
    /**
     * Internal server error
     */
    500: GatewayErrorResponse;
};

export type PostTextToImageError = PostTextToImageErrors[keyof PostTextToImageErrors];

export type PostTextToImageResponses = {
    /**
     * Successful generation
     */
    200: SingleGenerationResponse;
};

export type PostTextToImageResponse = PostTextToImageResponses[keyof PostTextToImageResponses];
