// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { PostAnimateData, PostAnimateErrors, PostAnimateResponses, PostAutoPromptData, PostAutoPromptErrors, PostAutoPromptResponses, PostEditByPromptData, PostEditByPromptErrors, PostEditByPromptResponses, PostRenderExteriorData, PostRenderExteriorErrors, PostRenderExteriorResponses, PostRenderInteriorData, PostRenderInteriorErrors, PostRenderInteriorResponses, PostStyleTransferData, PostStyleTransferErrors, PostStyleTransferResponses, PostTextToImageData, PostTextToImageErrors, PostTextToImageResponses, PostUpscale4kData, PostUpscale4kErrors, PostUpscale4kResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Render Interior
 *
 * Generate a photorealistic interior render from a 3D view export from any CAD or 3D modeling tool. Optionally guide the output with a text prompt.
 */
export const postRenderInterior = <ThrowOnError extends boolean = false>(options: Options<PostRenderInteriorData, ThrowOnError>): RequestResult<PostRenderInteriorResponses, PostRenderInteriorErrors, ThrowOnError> => (options.client ?? client).post<PostRenderInteriorResponses, PostRenderInteriorErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/render/interior',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Render Exterior
 *
 * Generate a photorealistic exterior render from a 3D view export from any CAD or 3D modeling tool. Optionally guide the output with a text prompt.
 */
export const postRenderExterior = <ThrowOnError extends boolean = false>(options: Options<PostRenderExteriorData, ThrowOnError>): RequestResult<PostRenderExteriorResponses, PostRenderExteriorErrors, ThrowOnError> => (options.client ?? client).post<PostRenderExteriorResponses, PostRenderExteriorErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/render/exterior',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Auto Prompt
 *
 * Analyze the input image and generate a detailed, comma-separated prompt describing its every aspect. Returns the generated prompt as text in output (not a URL). We highly recommend using it for pre-filling the prompt field of the render endpoints.
 */
export const postAutoPrompt = <ThrowOnError extends boolean = false>(options: Options<PostAutoPromptData, ThrowOnError>): RequestResult<PostAutoPromptResponses, PostAutoPromptErrors, ThrowOnError> => (options.client ?? client).post<PostAutoPromptResponses, PostAutoPromptErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/auto-prompt',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Edit by Prompt
 *
 * Edit an existing image with a natural-language instruction. The model applies the requested change while matching the input's aspect ratio. Returns the edited image URL.
 */
export const postEditByPrompt = <ThrowOnError extends boolean = false>(options: Options<PostEditByPromptData, ThrowOnError>): RequestResult<PostEditByPromptResponses, PostEditByPromptErrors, ThrowOnError> => (options.client ?? client).post<PostEditByPromptResponses, PostEditByPromptErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/edit-by-prompt',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Style Transfer
 *
 * Transfer the visual style of a reference image onto a source architectural image. Control the strength of the effect with the styleTransferStrength parameter.
 */
export const postStyleTransfer = <ThrowOnError extends boolean = false>(options: Options<PostStyleTransferData, ThrowOnError>): RequestResult<PostStyleTransferResponses, PostStyleTransferErrors, ThrowOnError> => (options.client ?? client).post<PostStyleTransferResponses, PostStyleTransferErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/style-transfer',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Animate Image
 *
 * Turn a single image into a short video or create a smooth transition between two images. Use the prompt to describe the camera motion. Returns a video URL in output.
 */
export const postAnimate = <ThrowOnError extends boolean = false>(options: Options<PostAnimateData, ThrowOnError>): RequestResult<PostAnimateResponses, PostAnimateErrors, ThrowOnError> => (options.client ?? client).post<PostAnimateResponses, PostAnimateErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/animate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upscale to 4K
 *
 * Upscale an image to 4K resolution while preserving details and sharpness. Accepts images up to 2K and outputs up to 4K or 8K.
 */
export const postUpscale4K = <ThrowOnError extends boolean = false>(options: Options<PostUpscale4kData, ThrowOnError>): RequestResult<PostUpscale4kResponses, PostUpscale4kErrors, ThrowOnError> => (options.client ?? client).post<PostUpscale4kResponses, PostUpscale4kErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/upscale-4k',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Text to Image
 *
 * Generate an architectural image from a text description. Specify output dimensions (128-2048px) and format. Use negativePrompt to exclude unwanted elements.
 */
export const postTextToImage = <ThrowOnError extends boolean = false>(options: Options<PostTextToImageData, ThrowOnError>): RequestResult<PostTextToImageResponses, PostTextToImageErrors, ThrowOnError> => (options.client ?? client).post<PostTextToImageResponses, PostTextToImageErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/text-to-image',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
